
title: Your awesome title
email: b0jko3@abv.bg
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/Jekyll-awesome-site"
# baseurl: ""
url: ""
github_username:  b0jko3

destination: docs

future: true
markdown: kramdown
plugins:
  - jekyll-feed

sass:
  sass_dir: assets/css

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - gulpfile.js
  - docs
  - node_modules
  - _sass
  - assets/css